"""Email functionality for SOTAforge - PDF generation and email delivery."""

import base64
import os
from datetime import datetime
from io import BytesIO
from typing import Any, Dict

import resend
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

from sotaforge.utils.logger import get_logger

logger = get_logger(__name__)


def generate_pdf(topic: str, result: Dict[str, Any]) -> bytes:
    """Generate PDF document for SOTA results.

    Args:
        topic: Research topic
        result: SOTA generation result

    Returns:
        PDF file as bytes

    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )

    # Container for the 'Flowable' objects
    elements = []

    # Define styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        spaceAfter=30,
        alignment=1,  # Center alignment
    )
    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]

    # Title
    title = Paragraph("State-of-the-Art Summary", title_style)
    elements.append(title)
    elements.append(Spacer(1, 0.2 * inch))

    # Topic
    topic_text = Paragraph(f"<b>Topic:</b> {topic}", heading_style)
    elements.append(topic_text)
    elements.append(Spacer(1, 0.2 * inch))

    # Metadata
    status = result.get("status", "unknown")
    generated_date = datetime.now().strftime("%B %d, %Y")

    metadata = f"""<b>Status:</b> {status}<br/>
    <b>Generated:</b> {generated_date}<br/>
    <b>Source:</b> <link href="https://github.com/elianmangin0/SOTAforge">SOTAforge</link>
    """
    elements.append(Paragraph(metadata, normal_style))
    elements.append(Spacer(1, 0.3 * inch))

    # Horizontal line
    elements.append(HRFlowable(width="100%", thickness=1, color="black"))
    elements.append(Spacer(1, 0.3 * inch))

    # Summary heading
    summary_heading = Paragraph("Summary", heading_style)
    elements.append(summary_heading)
    elements.append(Spacer(1, 0.2 * inch))

    # SOTA content - split into paragraphs
    sota_text = result.get("text", "No content available")
    paragraphs = sota_text.split("\n\n")

    for para in paragraphs:
        if para.strip():
            # Replace special characters for PDF
            para_clean = (
                para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            )
            p = Paragraph(para_clean, normal_style)
            elements.append(p)
            elements.append(Spacer(1, 0.1 * inch))

    # Footer
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(HRFlowable(width="100%", thickness=1, color="black"))
    elements.append(Spacer(1, 0.1 * inch))
    footer = Paragraph(
        "<i>This report was automatically generated by SOTAforge.</i>", normal_style
    )
    elements.append(footer)

    # Build PDF
    doc.build(elements)

    # Get the PDF bytes
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes


async def send_email(recipient: str, topic: str, result: Dict[str, Any]) -> None:
    """Send SOTA results via email with PDF and Markdown attachments using Resend.

    Args:
        recipient: Email address to send to
        topic: Research topic
        result: SOTA generation result

    Raises:
        Exception: If email sending fails

    """
    # Get Resend API key from environment
    resend_api_key = os.getenv("RESEND_API_KEY")
    sender_email = os.getenv("SENDER_EMAIL", "onboarding@resend.dev")

    if not resend_api_key:
        logger.warning("RESEND_API_KEY not configured, skipping email")
        return

    # Set API key
    resend.api_key = resend_api_key

    # Email subject and body
    status = result.get("status", "unknown")
    subject = f"SOTAforge: Your SOTA for '{topic}' is ready!"

    body = f"""Hello!

        Your State-of-the-Art (SOTA) summary for the topic "{topic}" has been generated.

        Status: {status}

        Please find attached:
        - PDF report (SOTA_{topic.replace(" ", "_")}.pdf)
        - Markdown file (SOTA_{topic.replace(" ", "_")}.md)

        Thank you for using SOTAforge!

        Best regards,
        The SOTAforge Team
        https://github.com/elianmangin0/SOTAforge
        """
    # Prepare attachments
    attachments = []

    # Generate and attach PDF
    try:
        pdf_bytes = generate_pdf(topic, result)
        pdf_base64 = base64.b64encode(pdf_bytes).decode("utf-8")
        pdf_filename = f"SOTA_{topic.replace(' ', '_')[:50]}.pdf"

        attachments.append(
            {
                "filename": pdf_filename,
                "content": pdf_base64,
            }
        )
        logger.info(f"PDF generated: {pdf_filename}")
    except Exception as e:
        logger.error(f"Failed to generate PDF: {str(e)}")

    # Attach Markdown
    try:
        sota_text = result.get("text", "No content available")
        md_base64 = base64.b64encode(sota_text.encode("utf-8")).decode("utf-8")
        md_filename = f"SOTA_{topic.replace(' ', '_')[:50]}.md"

        attachments.append(
            {
                "filename": md_filename,
                "content": md_base64,
            }
        )
        logger.info(f"Markdown attached: {md_filename}")
    except Exception as e:
        logger.error(f"Failed to attach Markdown: {str(e)}")

    # Send email using Resend
    try:
        params: Dict[str, Any] = {
            "from": sender_email,
            "to": [recipient],
            "subject": subject,
            "text": body,
        }

        if attachments:
            params["attachments"] = attachments

        response = resend.Emails.send(params)  # type: ignore[arg-type]
        logger.info(
            f"Email sent successfully to {recipient}"
            f" via Resend. ID: {response.get('id')}"
        )
    except Exception as e:
        logger.error(f"Failed to send email to {recipient}: {str(e)}")
        raise
