"""Email functionality for SOTAforge - PDF generation and email delivery."""

import os
from datetime import datetime
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from io import BytesIO
from typing import Any, Dict

import aiosmtplib
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

from sotaforge.utils.errors import ConfigurationError
from sotaforge.utils.logger import get_logger

logger = get_logger(__name__)


def generate_pdf(topic: str, result: Dict[str, Any]) -> bytes:
    """Generate PDF document for SOTA results.

    Args:
        topic: Research topic
        result: SOTA generation result

    Returns:
        PDF file as bytes

    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )

    # Container for the 'Flowable' objects
    elements = []

    # Define styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        spaceAfter=30,
        alignment=1,  # Center alignment
    )
    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]

    # Title
    title = Paragraph("State-of-the-Art Summary", title_style)
    elements.append(title)
    elements.append(Spacer(1, 0.2 * inch))

    # Topic
    topic_text = Paragraph(f"<b>Topic:</b> {topic}", heading_style)
    elements.append(topic_text)
    elements.append(Spacer(1, 0.2 * inch))

    # Metadata
    status = result.get("status", "unknown")
    generated_date = datetime.now().strftime("%B %d, %Y")

    metadata = f"""<b>Status:</b> {status}<br/>
    <b>Generated:</b> {generated_date}<br/>
    <b>Source:</b> <link href="https://github.com/elianmangin0/SOTAforge">SOTAforge</link>
    """
    elements.append(Paragraph(metadata, normal_style))
    elements.append(Spacer(1, 0.3 * inch))

    # Horizontal line
    elements.append(HRFlowable(width="100%", thickness=1, color="black"))
    elements.append(Spacer(1, 0.3 * inch))

    # Summary heading
    summary_heading = Paragraph("Summary", heading_style)
    elements.append(summary_heading)
    elements.append(Spacer(1, 0.2 * inch))

    # SOTA content - split into paragraphs
    sota_text = result.get("text", "No content available")
    paragraphs = sota_text.split("\n\n")

    for para in paragraphs:
        if para.strip():
            # Replace special characters for PDF
            para_clean = (
                para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            )
            p = Paragraph(para_clean, normal_style)
            elements.append(p)
            elements.append(Spacer(1, 0.1 * inch))

    # Footer
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(HRFlowable(width="100%", thickness=1, color="black"))
    elements.append(Spacer(1, 0.1 * inch))
    footer = Paragraph(
        "<i>This report was automatically generated by SOTAforge.</i>", normal_style
    )
    elements.append(footer)

    # Build PDF
    doc.build(elements)

    # Get the PDF bytes
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes


async def send_email(recipient: str, topic: str, result: Dict[str, Any]) -> None:
    """Send SOTA results via email with PDF and Markdown attachments.

    Args:
        recipient: Email address to send to
        topic: Research topic
        result: SOTA generation result

    Raises:
        Exception: If email sending fails

    """
    # Get SMTP configuration from environment variables
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER")
    smtp_password = os.getenv("SMTP_PASSWORD")
    sender_email = os.getenv("SENDER_EMAIL", smtp_user)

    if not smtp_user or not smtp_password:
        logger.warning("SMTP credentials not configured, skipping email")
        return

    # Create multipart message
    message = MIMEMultipart()
    if sender_email:
        message["From"] = sender_email
    else:
        raise ConfigurationError("Sender email is not configured.")
    message["To"] = recipient
    message["Subject"] = f"SOTAforge: Your SOTA for '{topic}' is ready!"

    # Email body
    status = result.get("status", "unknown")
    body = f"""Hello!
        Your State-of-the-Art (SOTA) summary for the topic "{topic}" has been generated.

        Status: {status}

        Please find attached:
        - PDF report (SOTA_{topic.replace(" ", "_")}.pdf)
        - Markdown file (SOTA_{topic.replace(" ", "_")}.md)

        Thank you for using SOTAforge!

        Best regards,
        The SOTAforge Team
        https://github.com/elianmangin0/SOTAforge
        """
    message.attach(MIMEText(body, "plain"))

    # Generate and attach PDF
    try:
        pdf_bytes = generate_pdf(topic, result)
        pdf_attachment = MIMEApplication(pdf_bytes, _subtype="pdf")
        pdf_filename = f"SOTA_{topic.replace(' ', '_')[:50]}.pdf"
        pdf_attachment.add_header(
            "Content-Disposition", "attachment", filename=pdf_filename
        )
        message.attach(pdf_attachment)
        logger.info(f"PDF generated: {pdf_filename}")
    except Exception as e:
        logger.error(f"Failed to generate PDF: {str(e)}")

    # Generate and attach Markdown
    try:
        sota_text = result.get("text", "No content available")
        md_attachment = MIMEText(sota_text, "plain")
        md_filename = f"SOTA_{topic.replace(' ', '_')[:50]}.md"
        md_attachment.add_header(
            "Content-Disposition", "attachment", filename=md_filename
        )
        message.attach(md_attachment)
        logger.info(f"Markdown attached: {md_filename}")
    except Exception as e:
        logger.error(f"Failed to attach Markdown: {str(e)}")

    # Send email
    try:
        await aiosmtplib.send(
            message,
            hostname=smtp_host,
            port=smtp_port,
            username=smtp_user,
            password=smtp_password,
            start_tls=True,
        )
        logger.info(f"Email sent successfully to {recipient} with attachments")
    except Exception as e:
        logger.error(f"Failed to send email to {recipient}: {str(e)}")
        raise
